### ISSUE TITLE
[4.x] Mod Hooks: Add right click - Create Script Hook

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-tool#115]
The naming is open for debate 😅 
With https://github.com/GodotModding/godot-mod-loader/pull/440 hooks can now be written in separate files.

> Ste — 16/11/2024 23:08
> would we rather open a second tree for hooks potentially doubling the vanilla file system again? or would we rather enforce a naming convention and live with the fact that hooks technically aren't extensions
> ```
> res://
> ├── game/
> │   └── scripts/
> │       └── main.gd
> └── mods-unpacked/
>     └── some-mod/
>         ├── extensions/
>         │   └── game/
>         │       └── scripts/
>         │           └── main.gd
>         └── hooks/
>             └── game/
>                 └── scripts/
>                     └── main.gd
> ```
> 
> or
> 
> ```
> .
> ├── game/
> │   └── scripts/
> │       └── main.gd
> └── mods-unpacked/
>     └── some-mod/
>         └── extensions/
>             └── game/
>                 └── scripts/
>                     ├── main.gd
>                     └── hooks-main.gd
> ```

We decided to go with the `-hook.gd` naming convention

**Comment by Qubus0** [comment]
gave it another think, we could also go for `main.hooks.gd`, that seems the cleanest "meaning wise" to me. might be personal preference though.

**Comment by KANAjetzt** [comment]
closed by #119

**Comment by KANAjetzt** [comment]
closed by #119
