### ISSUE TITLE
Open the Script Editor after a script extension is created

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-tool#47]
Similar to this:
https://github.com/GodotModding/godot-mod-tool/blob/cbd902ade87673fd260bd509371a0496ab71c789/addons/mod_tool/interface/create_mod/create_mod.gd#L50-L53

**Comment by Qubus0** [comment]
Which one will be opened if multiple are created? All of them? None? First or last?

**Comment by KANAjetzt** [comment]
Open all and focus the first one?
