### ISSUE TITLE
Refactor Create Mod Popup

### ISSUE THREAD

**Issue by KANAjetzt** [GodotModding/godot-mod-tool#49]
Change from one input mod id to:

- [ ] namespace
- [ ] name

A - 👍 
```
[ ModAuthor ] - [ ModName ]
```

B - 👀 
```
namespace: [ ModAuthor ]  
name: [ ModName ]
```

**Comment by Qubus0** [comment]
B allows to reuse the inputs we already have and is clearer. 
we can add a label just below that that shows the mod id in the [ ]-[ ] format
